sudo: no

language: python

addons:
  postgresql: "9.3"

env:
  - TOXENV=py27-1.6-sqlite3
  - TOXENV=py27-1.6-postgresql
  - TOXENV=py27-1.7-sqlite3
  - TOXENV=py27-1.7-postgresql
  - TOXENV=py27-master-sqlite3
  - TOXENV=py27-master-postgresql
  - TOXENV=py32-1.6-sqlite3
  - TOXENV=py32-1.6-postgresql
  - TOXENV=py32-1.7-sqlite3
  - TOXENV=py32-1.7-postgresql
  - TOXENV=py33-1.6-sqlite3
  - TOXENV=py33-1.6-postgresql
  - TOXENV=py33-1.7-sqlite3
  - TOXENV=py33-1.7-postgresql
  - TOXENV=py34-1.7-sqlite3
  - TOXENV=py34-1.7-postgresql
  - TOXENV=py34-master-sqlite3
  - TOXENV=py34-master-postgresql

matrix:
  fast_finish: true
  include:
    - python: 2.6
      env: TOXENV=py26-1.6-sqlite3
    - python: 2.6
      env: TOXENV=py26-1.6-postgresql
  allow_failures:
    - env: TOXENV=py27-master-sqlite3
    - env: TOXENV=py27-master-postgresql
    - env: TOXENV=py34-master-sqlite3
    - env: TOXENV=py34-master-postgresql

before_script:
  - if echo $TOXENV | grep -E 'postgresql' -q; then psql -U postgres -c "CREATE DATABASE tenancy;"; fi

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls
