branches:
  only:
    - master

language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO="django>=1.5,<1.6" SETTINGS=sqlite3
  - DJANGO="django>=1.5,<1.6" SETTINGS=postgresql_psycopg2
  - DJANGO="django>=1.6,<1.7" SETTINGS=sqlite3
  - DJANGO="django>=1.6,<1.7" SETTINGS=postgresql_psycopg2
  - DJANGO="django>=1.7,<1.8" SETTINGS=sqlite3
  - DJANGO="django>=1.7,<1.8" SETTINGS=postgresql_psycopg2
  - DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=sqlite3
  - DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=postgresql_psycopg2

matrix:
  exclude:
    - python: 2.6
      env: DJANGO="https://github.com/django/django/archive/stable/1.7.x.tar.gz" SETTINGS=sqlite3
    - python: 2.6
      env: DJANGO="https://github.com/django/django/archive/stable/1.7.x.tar.gz" SETTINGS=postgresql_psycopg2
    - python: 2.6
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=sqlite3
    - python: 2.6
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=postgresql_psycopg2
  allow_failures:
    - env: DJANGO="django>=1.7,<1.8" SETTINGS=sqlite3
    - env: DJANGO="django>=1.7,<1.8" SETTINGS=postgresql_psycopg2
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=sqlite3
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz" SETTINGS=postgresql_psycopg2

before_script:
  - export PGUSER='postgres'
  - if echo $SETTINGS | grep 'postgresql' -q; then psql -c 'CREATE DATABASE tenancy;' -U postgres; fi

install:
  - pip install $DJANGO coveralls django-hosts -q
  - if echo $SETTINGS | grep 'psycopg2' -q; then pip install psycopg2 -q; fi
  - if python --version 2>&1 > /dev/null | grep -E '^Python 2' -q; then
      pip install django-mutant;
    else
      echo "django-mutant has not been ported to Python 3 yet.";
    fi

script:
  - python -Wonce `which coverage` run `which django-admin.py` test tenancy --pythonpath=`pwd` --settings=test_settings.$SETTINGS -v2

after_success:
  - coverage report -m
  - coveralls
