dist: trusty
sudo: no

language: python

addons:
  postgresql: "9.6"

env:
  - TOXENV=flake8
  - TOXENV=isort

cache: pip

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-1.8-sqlite3
    - python: 2.7
      env: TOXENV=py27-1.8-postgresql
    - python: 2.7
      env: TOXENV=py27-1.9-sqlite3
    - python: 2.7
      env: TOXENV=py27-1.9-postgresql
    - python: 2.7
      env: TOXENV=py27-1.10-sqlite3
    - python: 2.7
      env: TOXENV=py27-1.10-postgresql
    - python: 2.7
      env: TOXENV=py27-1.11-sqlite3
    - python: 2.7
      env: TOXENV=py27-1.11-postgresql

    - python: 3.4
      env: TOXENV=py34-1.8-sqlite3
    - python: 3.4
      env: TOXENV=py34-1.8-postgresql
    - python: 3.4
      env: TOXENV=py34-1.9-sqlite3
    - python: 3.4
      env: TOXENV=py34-1.9-postgresql
    - python: 3.4
      env: TOXENV=py34-1.10-sqlite3
    - python: 3.4
      env: TOXENV=py34-1.10-postgresql
    - python: 3.4
      env: TOXENV=py34-1.11-sqlite3
    - python: 3.4
      env: TOXENV=py34-1.11-postgresql

    - python: 3.5
      env: TOXENV=py35-1.8-sqlite3
    - python: 3.5
      env: TOXENV=py35-1.8-postgresql
    - python: 3.5
      env: TOXENV=py35-1.9-sqlite3
    - python: 3.5
      env: TOXENV=py35-1.9-postgresql
    - python: 3.5
      env: TOXENV=py35-1.10-sqlite3
    - python: 3.5
      env: TOXENV=py35-1.10-postgresql
    - python: 3.5
      env: TOXENV=py35-1.11-sqlite3
    - python: 3.5
      env: TOXENV=py35-1.11-postgresql
    - python: 3.5
      env: TOXENV=py35-master-sqlite3
    - python: 3.5
      env: TOXENV=py35-master-postgresql

    - python: 3.6
      env: TOXENV=py36-1.11-sqlite3
    - python: 3.6
      env: TOXENV=py36-1.11-postgresql
    - python: 3.6
      env: TOXENV=py36-master-sqlite3
    - python: 3.6
      env: TOXENV=py36-master-postgresql
  allow_failures:
    - env: TOXENV=py35-master-sqlite3
    - env: TOXENV=py35-master-postgresql
    - env: TOXENV=py36-master-sqlite3
    - env: TOXENV=py36-master-postgresql

before_script:
  - if echo $TOXENV | grep -E 'postgresql' -q; then psql -U postgres -c "CREATE DATABASE tenancy;"; fi

install:
  - pip install tox

script:
  - tox

after_success:
  - coveralls
