sudo: no

language: python

addons:
  postgresql: "9.3"

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27-1.8-sqlite3
  - TOXENV=py27-1.8-postgresql
  - TOXENV=py27-1.9-sqlite3
  - TOXENV=py27-1.9-postgresql
  - TOXENV=py27-master-sqlite3
  - TOXENV=py27-master-postgresql
  - TOXENV=py32-1.8-sqlite3
  - TOXENV=py32-1.8-postgresql
  - TOXENV=py33-1.8-sqlite3
  - TOXENV=py33-1.8-postgresql
  - TOXENV=py34-1.8-sqlite3
  - TOXENV=py34-1.8-postgresql
  - TOXENV=py34-1.9-sqlite3
  - TOXENV=py34-1.9-postgresql
  - TOXENV=py34-master-sqlite3
  - TOXENV=py34-master-postgresql

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=py35-1.8-sqlite3
    - python: 3.5
      env: TOXENV=py35-1.8-postgresql
    - python: 3.5
      env: TOXENV=py35-1.9-sqlite3
    - python: 3.5
      env: TOXENV=py35-1.9-postgresql
    - python: 3.5
      env: TOXENV=py35-master-sqlite3
    - python: 3.5
      env: TOXENV=py35-master-postgresql
  allow_failures:
    - env: TOXENV=py27-master-sqlite3
    - env: TOXENV=py27-master-postgresql
    - env: TOXENV=py34-master-sqlite3
    - env: TOXENV=py34-master-postgresql
    - env: TOXENV=py35-master-sqlite3
    - env: TOXENV=py35-master-postgresql

before_script:
  - if echo $TOXENV | grep -E 'postgresql' -q; then psql -U postgres -c "CREATE DATABASE tenancy;"; fi

install:
  - pip install tox "virtualenv<14.0"

script:
  - tox

after_success:
  - coveralls
